export default {
    industries: [
        "Architecture",
        "Business/Consulting/Management",
        "Creative Arts/Design",
        "Energy/Utilities",
        "Engineering/Manufacturing",
        "Environment/Agriculture",
        "Health/Social Care",
        "Hospitality/Tourism/Sport",
        "IT/Information Service",
        "Law",
        "Marketing/Advertising/PR",
        "Media/Publishing",
        "NGO/Development/Social Enterprise",
        "Property/Construction",
        "Public Sector",
        "Recruitment/HR/Coaching",
        "Retail/Sales",
        "Science/Pharmaceuticals",
        "Teaching/Education",
        "Transport/Logistics",
        "Finance/Accounting",
    ],
};
